//
//  BDFCommentAPIConstant.h
//  BDFMobileCollect
//
//  Created by 张声扬 on 2017/5/26.
//  Copyright © 2017年 zhangshengyang. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface BDFCommentAPIConstant : NSObject


/**
 示例bing每日壁纸基本API
 */
UIKIT_EXTERN NSString *const BDFBINGIMAGEAPI;

UIKIT_EXTERN NSString *const BDFLOGINBASEAPI;
UIKIT_EXTERN NSString *const BDFHOMEPAGEHOTNNEWS;
UIKIT_EXTERN NSString *const BDFHOMEPAGEHOTNNEWSUPS;
UIKIT_EXTERN NSString *const BDFHOMEPAGEHOTNNEWSREMOVEUPS;
UIKIT_EXTERN NSString *const BDFHOMEPAGEHOTNNEWSADD;
UIKIT_EXTERN NSString *const BDFHOMEPAGEHOTNNEWSDELADD;
UIKIT_EXTERN NSString *const BDFHOMEPAGEHOTNNEWSCOMMENT;
UIKIT_EXTERN NSString *const BDFHOMEPAGEHOTNNEWSCOMMENTINDEX;
UIKIT_EXTERN NSString *const BDFHOMESEARCHSUGGEST;
UIKIT_EXTERN NSString *const BDFHOMESEARCHPUBLISH;

@end
