//
//  BDFCommentAPIConstant.h
//  BDFMobileCollect
//
//  Created by 张声扬 on 2017/5/26.
//  Copyright © 2017年 zhangshengyang. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface BDFCommentAPIConstant : NSObject


/**
 示例bing每日壁纸基本API
 */
UIKIT_EXTERN NSString *const BDFBINGIMAGEAPI;

UIKIT_EXTERN NSString *const BDFLOGINBASEAPI;
UIKIT_EXTERN NSString *const BDFHOMEPAGEHOTNNEWS;
UIKIT_EXTERN NSString *const BDFHOMEPAGEHOTNNEWSUPS;
UIKIT_EXTERN NSString *const BDFHOMEPAGEHOTNNEWSREMOVEUPS;
UIKIT_EXTERN NSString *const BDFHOMEPAGEHOTNNEWSADD;
UIKIT_EXTERN NSString *const BDFHOMEPAGEHOTNNEWSDELADD;
UIKIT_EXTERN NSString *const BDFHOMEPAGEHOTNNEWSCOMMENT;
UIKIT_EXTERN NSString *const BDFHOMEPAGEHOTNNEWSCOMMENTINDEX;
UIKIT_EXTERN NSString *const BDFHOMESEARCHSUGGEST;
UIKIT_EXTERN NSString *const BDFHOMESEARCHPUBLISH;
UIKIT_EXTERN NSString *const BDFMEDATA;
UIKIT_EXTERN NSString *const BDFHOMENEWSCATEGORY;
UIKIT_EXTERN NSString *const BDFHOMEMOSTHOTLIST;
UIKIT_EXTERN NSString *const BDFHOMECATEGORY42MENU;
UIKIT_EXTERN NSString *const BDFHOMECATEGORY42;
UIKIT_EXTERN NSString *const BDFHOMECATEGORY42HOT;
UIKIT_EXTERN NSString *const BDFHOMECATEGORY42CATEGORY;
UIKIT_EXTERN NSString *const BDFHOMECATEGORYSCOFF;
UIKIT_EXTERN NSString *const BDFHOMECATEGORYTOPICLIST;
UIKIT_EXTERN NSString *const BDFHOMECATEGORYTOPICLISTDETAIL;
UIKIT_EXTERN NSString *const BDFHOMECATEGORYPICTUREHOTLIST;
UIKIT_EXTERN NSString *const BDFHOMECATEGORYPICTURENEWLIST;
UIKIT_EXTERN NSString *const BDFHOMECATEGORY1024HOTLIST;
UIKIT_EXTERN NSString *const BDFHOMECATEGORY1024NEWLIST;
UIKIT_EXTERN NSString *const BDFHOMECATEGORYQAHOTLIST;
UIKIT_EXTERN NSString *const BDFHOMECATEGORYQANEWLIST;
UIKIT_EXTERN NSString *const BDFHOMECATEGORYVIDEOHOTLIST;
UIKIT_EXTERN NSString *const BDFHOMECATEGORYVIDEONEWLIST;
UIKIT_EXTERN NSString *const BDFHOMECATEGORYFLOWLIST;
UIKIT_EXTERN NSString *const BDFHOMECATEGORYMANLIST;
UIKIT_EXTERN NSString *const BDFHOMECATEGORYPUBLISHLIST;
UIKIT_EXTERN NSString *const BDFHOMECATEGORYCOMMENTLIST;
UIKIT_EXTERN NSString *const BDFHOMEHISTORYLIST;
UIKIT_EXTERN NSString *const BDFHOMELIKELIST;
UIKIT_EXTERN NSString *const BDFHOMECOMMENTLIST;
UIKIT_EXTERN NSString *const BDFHOMEPUBLISHLIST;

@end
